### ISSUE TITLE
Please consider renaming this theme

### ISSUE THREAD

**Issue by unixorn** [shirnschall/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Also, it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by shirnschall** [comment]
Hi, 
cool project at https://github.com/unixorn/awesome-zsh-plugins.

I have now renamed the theme based on my GitHub username and updated the readme to reflect this change.

I have also included a license file. I have chosen the MIT license, although I am open to change this to a more permissive license if necessary.

Please let me know if you have other issues/suggestions.

—Sebastian

**Comment by unixorn** [comment]
Thanks for updating your theme, I've added it to the list.
